// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orbita.Challenge.Infra.Infra;

namespace Orbita.Challenge.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Orbita.Challenge.Core.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7094fa95-2959-40c8-b9ad-329e36410902"),
                            Cpf = "19857635408",
                            Email = "vinicius.estudos@escola.com",
                            Name = "Vinicius Rocha"
                        },
                        new
                        {
                            Id = new Guid("e67b1e3f-a26c-43d8-a70c-027a0402d2fe"),
                            Cpf = "78965325872",
                            Email = "isabelle.estudos@escola.com",
                            Name = "Isabelle"
                        },
                        new
                        {
                            Id = new Guid("368f8ce8-d6a8-4d71-a789-f067e1c2cab5"),
                            Cpf = "755634198635",
                            Email = "guilherme.estudos@escola.com",
                            Name = "Guilherme"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
